### ISSUE TITLE
Issue Resolved: QBCore Update

### ISSUE THREAD

**Issue by Comboz2007** [nagsterFVZ/fjh-sling#8]
Hello All, recently I've been developing my own QBCore Server and loved to have a Weapons Sling resource, as many of your know this is one of the best and only QBCore Sling Scripts but it is currently outdated. I have just fixed it and just a few changes need to be made in order for the script to work. 

Just follow these instructions for the resource to work.

**1.** Open the **fjh-sling-master** folder and open to the following path _fxmanifest.lua_ and proceed to open the file.

Edit the file by heading to **Line #8**

Delete the text **'@qb-core/import.lua',**

Save the file and go back to the original directory.

**2.** Open the **server.lua** file and at the top of the file make 2 Lines above the previous one.

At the very top place the following Line exactly the same.

local QBCore = exports['qb-core']:GetCoreObject()

**_After this step your code should look similar to this_**

local QBCore = exports['qb-core']:GetCoreObject()

QBCore.Commands.Add("sling", "Change weapon sling position", {}, false, function(source, args)
	TriggerClientEvent("mg-weapon-sling:client:changeSling", source)
end)

**3.** Now open the **client.lua** file and at the very top create an extra line and place the line at the very top line:

local QBCore = exports['qb-core']:GetCoreObject()

_**Your code should look like this from the top few lines:**_

local QBCore = exports['qb-core']:GetCoreObject()
local attached_weapons = {}
local hotbar = {}
local sling = "Back"
local playerLoaded = false

After you have completed these steps start the resource as usual and the resource should be compatible. Feel free to send me any enquires if the solution doesn't work or for any extra help.

**Comment by code-universe-unit** [comment]
> Hello All, recently I've been developing my own QBCore Server and loved to have a Weapons Sling resource, as many of your know this is one of the best and only QBCore Sling Scripts but it is currently outdated. I have just fixed it and just a few changes need to be made in order for the script to work.
> 
> Just follow these instructions for the resource to work.
> 
> **1.** Open the **fjh-sling-master** folder and open to the following path _fxmanifest.lua_ and proceed to open the file.
> 
> Edit the file by heading to **Line #8**
> 
> Delete the text **'@qb-core/import.lua',**
> 
> Save the file and go back to the original directory.
> 
> **2.** Open the **server.lua** file and at the top of the file make 2 Lines above the previous one.
> 
> At the very top place the following Line exactly the same.
> 
> local QBCore = exports['qb-core']:GetCoreObject()
> 
> **_After this step your code should look similar to this_**
> 
> local QBCore = exports['qb-core']:GetCoreObject()
> 
> QBCore.Commands.Add("sling", "Change weapon sling position", {}, false, function(source, args) TriggerClientEvent("mg-weapon-sling:client:changeSling", source) end)
> 
> **3.** Now open the **client.lua** file and at the very top create an extra line and place the line at the very top line:
> 
> local QBCore = exports['qb-core']:GetCoreObject()
> 
> _**Your code should look like this from the top few lines:**_
> 
> local QBCore = exports['qb-core']:GetCoreObject() local attached_weapons = {} local hotbar = {} local sling = "Back" local playerLoaded = false
> 
> After you have completed these steps start the resource as usual and the resource should be compatible. Feel free to send me any enquires if the solution doesn't work or for any extra help.

It's working, Thank's man

**Comment by nagsterFVZ** [comment]
Seeing as this repo is getting attention again, I went and merged a PR to fix the above, should also just work out of the box now. Thanks for your guide @Comboz2007 explaining how to use it for the time being.
